XPATHS = {"clients": "/html/body/div[1]/div[1]/div/ul[1]/li[2]",
          "add_client": "/html/body/div[1]/div[4]/div/div[1]/span/button",
          "add_client_client": "/html/body/div[1]/div[4]/div/div[1]/span/ul/li[1]/a",
          "add_client_firstname": "/html/body/div[7]/div/form/div/div[2]/div/div[1]/div[1]/input",
          "add_client_lastname": "/html/body/div[7]/div/form/div/div[2]/div/div[1]/div[2]/input",
          "add_client_dob": "/html/body/div[7]/div/form/div/div[2]/div/div[1]/div[3]/div/div[1]/input",
          "add_client_spouse_firstname": "/html/body/div[7]/div/form/div/div[2]/div/div[2]/div[1]/input",
          "add_client_spouse_lastname": "/html/body/div[7]/div/form/div/div[2]/div/div[2]/div[2]/input",
          "add_client_spouse_dob": "/html/body/div[7]/div/form/div/div[2]/div/div[2]/div[3]/div/div[1]/input",
          "add_client_submit": "/html/body/div[7]/div/form/div/div[3]/button[2]",
          "facts": "/html/body/div[1]/div[4]/div/ul/li[2]/a",
          "facts_add": "/html/body/div[1]/div[8]/div[2]/div[2]/div/div/div/div[1]/a",
          "child": "/html/body/div[1]/div[8]/div[2]/div[2]/div/div/div/div[1]/ul/li[2]/a",
          "childname": "/html/body/div[1]/div[8]/div[2]/div[2]/div/div/div/div[1]/div/div[3]/form/div[1]/input",
          "child_dob": "/html/body/div[1]/div[8]/div[2]/div[2]/div/div/div/div[1]/div/div[3]/form/div[3]/input",
          "childgender": "/html/body/div[1]/div[8]/div[2]/div[2]/div/div/div/div[1]/div/div[3]/form/div[4]/div/select",
          "childsave": "/html/body/div[1]/div[8]/div[2]/div[2]/div/div/div/div[1]/div/div[3]/form/div[7]/button"
          }
